name: computer-vision
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - jupyterlab==4.0.2
  - opencv==4.7.0
  - matplotlib==3.7.2
  - scikit-learn==1.2.2
  - scikit-image==0.19.3
  - ipywidgets==8.0.4
  - pytorch==2.0.1
  - torchvision==0.15.2
  - torchaudio==2.0.2
  - pytorch-cuda==11.7
  - lightning==2.0.6
  - torchmetrics==0.11.4
  - tqdm==4.65.0
  - torchinfo==1.8.0
  - pip
  - pip:
    - dlib-binary==19.21.99
    - tensorboardx==2.6.1
